### ISSUE TITLE
Kein Mailversand mehr nach Installation 1.6.5

### ISSUE THREAD

**Issue by raintausdu** [jens-maus/hm_email#1]
Hi

nach der Installation des Mail Addon 1.6.5 auf der RaspberryMatic können keine Mails mehr versendet werden.
Der Mail-Test bringt eine Fehlermeldung im HTML Format. Die Meldung kann ich leider nicht rauskopieren.
Im Message Log steht nichts womit ich mir selber helfen kann.
Wo kann ich noch nachsehen?
Danke
Gruß

**Comment by jens-maus** [comment]
Inzwischen gibt es doch version 1.6.6 die diese Probleme beheben sollte. Bitte diese Version installieren.
