### ISSUE TITLE
Can't get attachment (snapshot 1) to work

### ISSUE THREAD

**Issue by x-jokay** [jens-maus/hm_email#10]
Hellu

I have the following setup:
* [Email CCU Addon 1.6.8c](https://github.com/jens-maus/hm_email/releases/tag/1.6.8c) 
* CCU2

I'm trying to sent an email using attachment `snapshot 1` but can't get it work.

Emails without attachments work and I get a log entry on the tab `Help` `Email-Log`.

When I enable the attachment `snapshot 1` the email won't be sent and I see a `404 - Not Found` error on the tab `Help` `Email-Log`.

Tried the following without success:

* `snapshot 1` setting path, user and pass
  `http://{ip}/cgi-bin/snapshot.cgi`

* `snapshot 1` setting path including user and pass
  `http://{user}:{pass}@{ip}/cgi-bin/snapshot.cgi`

* `snapshot` setting path including user and pass

* `download` setting path including user and pass

Can I somehow get a more verbose logging? 😉

**Comment by x-jokay** [comment]
What I get from `/var/log/messages`

```sh
Jun 17 15:01:50 homematic-ccu2 user.err email: child process exited abnormally
Jun 17 15:01:50 homematic-ccu2 daemon.info cuxd[5921]: system(/etc/config/addons/email/email 02) exit(1) 1s
```

**Comment by x-jokay** [comment]
And when sending the email without attachment there is a `/var/log/email.log` but after enabling and sending the first email with attachment the file `/var/log/email.log` does no longer exist.

**Comment by HMside** [comment]
Das Logging müsste ich in der Tat noch optimieren. Was dein Problem mit dem Snapshot angeht, wären etwas mehr Details hilfreich. 

- Was für eine Cam verwendest Du?
- Wie sieht der funktionierende Snapshot Browser Aufruf auf?

**Comment by x-jokay** [comment]
Camera type is `Dahua` and the working request is `http://{user}:{pass}@{ip}/cgi-bin/snapshot.cgi`.

**Comment by x-jokay** [comment]
This request works in the browser but not for hm_email too:

```sh
http://{ip}/cgi-bin/snapshot.cgi?loginuse={user}&loginpas={pass}
```

**Comment by x-jokay** [comment]
When I execute the command as done in the script for `Snapshot 1` on the `CCU2` ...

```sh
wget --no-check-certificate -r -nd -A jpg,jpeg,png,cgi --user={user} --password={pass} --auth-no-challenge -P /usr/local/etc/config/addons/email/tmp/ "https://{ip}/cgi-bin/snapshot.cgi"

...

HTTP request sent, awaiting response... 401 Unauthorized
Authorization failed.
```

When executing the same command on another device it works:

```sh
wget --no-check-certificate -r -nd -A jpg,jpeg,png,cgi --user={user} --password={pass} --auth-no-challenge -P /home/system/Downloads/hm_email/ "https://{ip}/cgi-bin/snapshot.cgi"

...

HTTP request sent, awaiting response... 200 OK
Length: 912416 (891K) [image/jpeg]
Saving to: ‘/home/system/Downloads/hm_email/snapshot.cgi’

snapshot.cgi        100%[===================>] 891.03K   726KB/s    in 1.2s    

2019-06-20 14:14:26 (726 KB/s) - ‘/home/system/Downloads/hm_email/snapshot.cgi’ saved [912416/912416]

FINISHED --2019-06-20 14:14:26--
Total wall clock time: 11s
Downloaded: 1 files, 891K in 1.2s (726 KB/s)
```

**Comment by x-jokay** [comment]
`CCU2` has `wget 1.13.4`
`CCU3` has `wget 1.19.5`
and on the other device it was `wget 1.18`.

Seems to be a `wget` version problem in my case.

**Comment by x-jokay** [comment]
The problem seems to be the `Digest Authentication`, see [here](https://www.unix.com/302663501-post2.html?s=9143cf95d13a1a87e8a387011949713e).

I ended up doing a workaround using `curl`.

```tcl
dom.GetObject("CUxD.CUX2801001:1.CMD_SETS").State("LD_LIBRARY_PATH=/usr/local/addons/cuxd");

dom.GetObject("CUxD.CUX2801001:1.CMD_EXEC").State("/usr/local/addons/cuxd/curl -k -X GET --digest -u {user}:{pass} -o /tmp/snapshot.jpg 'https://{ip}/cgi-bin/snapshot.cgi' && /etc/config/addons/email/email 02");
```

And set on the email template `02` as attachment type `CCU-File` and as path `/tmp/snapshot.jpg`.

You may want to add `curl` as a second option one day 😉
