### ISSUE TITLE
AttNewName nicht initialisiert

### ISSUE THREAD

**Issue by wagner4u** [jens-maus/hm_email#2]
Hallo,
habe die neue Version 1.6.7 installiert in yahm auf rasperrypi 3.
Konnte aber immer nur die Email 01 versenden.
Bei allen anderen kam:
... user.err email: can't read "AttNewName": no such variable

Ich habe unter Zeile 118 im Script 'email' folgendes ergänzt, um die Variable AttNewName zu initialisieren:
...
**set AttName [file tail $mailAttachment]
set AttNewName ""**                 
...

Jetzt funktioniert es. Kannst Du das ergänzen ?
Gruss,
wagner4u

**Comment by hdering** [comment]
Hallo,
ich bekomme ebenfalls die gleiche Fehlermeldung. Nach Eintragung von "set AttNewName """ wie @wagner4u geschrieben hat, bekomme ich diese nicht mehr. Jedoch erhalte ich jetzt folgende Fehlermeldung (via syslog):
can't read "v3": no such variable 

Jemand eine Idee wo das definiert werden muss?

**Comment by hdering** [comment]
Die Fehlermeldung kommt ca. jede Stunde.

**Comment by HMside** [comment]
@wagner4u 
Sorry das ich mich erst jetzt hier melde. Die Problematik mit "AttNewName" habe ich kurz nach dem Update auch erkannt. Wird in der nächsten Version gefixt.

Besser ist allerdings: https://github.com/jens-maus/hm_email/commit/1b365554faeab45133de548ec16f813286cfbd28

@hdering 
Die Fehlermeldung "can't read "v3": no such variable" wird erscheinen, weil Du die Variable v3 im Reiter Tcl nicht deklariert hast. Alternativ sofern nicht benötigt in der Vorlage Tcl deaktivieren bzw. $v3 aus dem Mail Text löschen. Bei weiteren Fragen bitte den Support Thread nutzen: https://homematic-forum.de/forum/viewtopic.php?f=41&t=18610
