### ISSUE TITLE
Mail templates

### ISSUE THREAD

**Issue by raintausdu** [jens-maus/hm_email#4]
Hallo Jens

Ich habe die 1.6.7c installiert. Jetzt ist mir aufgefallen das ich die Mail templates nicht verändern kann.
Angezeigt werden mir diese aber mit den Veränderungen - gesendet ohne.

Woran liegt das? Wie kann ich das beheben?
Danke Gruß 
Bastian

**Comment by HMside** [comment]
Hallo Bastian,

bitte hier lesen: https://homematic-forum.de/forum/viewtopic.php?t=18610
