### ISSUE TITLE
Problem after Upgrade to 1.6.7c 

### ISSUE THREAD

**Issue by FloWord** [jens-maus/hm_email#5]
After Upgrade to 1.6.7c, i can not open the Email Addon correctly, see that printscreen, i see only a blank white page.
just for info: The setting still here, the mails are send out.
Thanks for any help.

![email-addond](https://user-images.githubusercontent.com/21309911/28607553-b52e1886-71dc-11e7-9e37-732a157dae9f.jpg)

**Comment by HMside** [comment]
Bitte hier lesen: https://homematic-forum.de/forum/viewtopic.php?t=18610
