### ISSUE TITLE
System variables in email using tcl-variables

### ISSUE THREAD

**Issue by wagner4u** [jens-maus/hm_email#6]
Hi,
I want to use the value of a homematic systemvariable within the email using tcl-script.

my rega-script is:
>>>>>>>>>>>>>>>>>>>>>>>
load tclrega.so

array set values [rega_script {
...
var v4 = dom.GetObject("anwesend").Value();
} ]

....
set v4 $values(v4)
<<<<<<<<<<<<<<<<<<<<<<<
The other values of a sensor work fine but not a system variable.
The value in the email is: null

What is wrong with the script ? How to add system variables here.

**Comment by HMside** [comment]
Für Support Anfragen bitte das Forum nutzen: https://homematic-forum.de/forum/viewtopic.php?f=41&t=18610

Hier bitte nur verifizierte Fehler melden. Danke
