### ISSUE TITLE
plugin verbleibt in der Systemsteuerung nach uninstall

### ISSUE THREAD

**Issue by 150d** [jens-maus/hm_email#8]
Hallo,

ich habe das email-Plugin deinstalliert und die CCU2 neu gestartet. Trotzdem erscheint das Modul "Email" weiterhin in der Systemsteuerung. Ein Klick darauf führt nur noch zu einem 404-Fehler.

Wie kann der Eintrag entfernt werden?

MfG

**Comment by HMside** [comment]
Vermutlich den Browser Cache nicht geleert. Falls das nicht reicht, bitte nochmal mal die aktuelle Version installieren und erneut deinstallieren.

**Comment by 150d** [comment]
Nein, das war es beides nicht: Erneut versucht mit install/uninstall v1.6.8c, Browser-Cache mehrmals explizit gelöscht, Browser neu gestartet - das Modul taucht weiterhin auf.

**Comment by 150d** [comment]
Gibt es für dieses Problem inzwischen einen Lösungsansatz?

**Comment by HMside** [comment]
Du kannst den Eintrag dann lediglich manuell entfernen. Dieser ist in /usr/local/etc/config/ hm_addons.cfg zu finden. Den folgenden Part musst Du aus dem cfg-File entfernen:
`email {CONFIG_URL /addons/email CONFIG_DESCRIPTION {de {<li>Email-Integration</li><li>Alarmierung und Weiterleitung von Systemzustaenden</li><li>Einfache Benachrichtigungen</li><li>...</li>} en {<li>Email-Integration</li><li>Alerting and routing of System-States</li><li>Simple Notifications</li><li>...</li>}} ID email CONFIG_NAME "Email"`

**Comment by 150d** [comment]
Danke, diese Informationen haben mir gefehlt.

In dieser Datei herrscht bei mir großes Chaos: Die Zeilen für das email-Plugin sind dort mindestens ein Dutzend mal eingetragen. Offenbar wurde bei jeder Installation des Plugins ein eintrag hinzugefügt, aber bei der Deinstallation niemals einer gelöscht.

Nachdem ich den Text gelöscht hatte, war der Eintrag im Menü sofort verschwunden (ohne Neustart der CCU2.) Ausserdem reagiert das Webinterface jetzt deutlich flotter als zuvor. Irgendetwas hatte sich da also gründlich verhakt.

Danke für die Hilfe!
