### ISSUE TITLE
Email addon 1.68c und ccu3 fehler

### ISSUE THREAD

**Issue by alero63** [jens-maus/hm_email#9]
Hi,
würde gerne dieses addon installieren damit ich mir per mail den Batterie status zukommen lassen kann. Leider lässt sich das addon nicht auf meine ccu3(3.41.11) einbinden. Nach dem Hochladen ist die ccu3 nicht mehr ansprechbar. Nach einem reboot kann ich wieder normal arbeiten. Das addin ist nicht installiert.
--

**Comment by Hypnos3** [comment]
Wenn du eine CCU3 hast kannst du dir auch gerne mal RedMatic ansehen. Damit lasse ich mir Mails über den Batterie status zusenden.

**Comment by HMside** [comment]
Dies dürfte ein Problem der 3.41.11 gewesen sein und somit nicht mehr bestehen.

**Comment by DaTommy83** [comment]
Das Problem besteht bei mir auch bei aktueller Firmware 3.49.17.
Wo kann das Problem sein?

**Comment by corbeau-jr** [comment]
Ich habe das gleiche Problem auch mit anderen Apps: die CCU3 hängt sich beim / nach dem Hochladen der Erweiterung auf und kann erst durch einen Neustart wiederbelebt werden. Bei mehreren Versuchen und Hängern klappt es dann irgendwann doch...
